spring:
  application:
    name: todolist
  datasource:
    url: jdbc:h2:mem:todoList
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-ui

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    enabled: true